# `latexmk` in this folder builds the CV with LuaLaTeX + biber.
# Intermediate files go to build/; the PDF goes straight to the website assets.
$pdf_mode = 4;
@default_files = ('cv.tex');
$jobname = 'CV_ChoiYJ';
$aux_dir = 'build';
$out_dir = '../assets/pdf';
$emulate_aux = 1;
